services:
  - type: web
    name: docker-study-hub
    runtime: docker
    plan: free
    dockerfilePath: ./copy-image/Dockerfile
    dockerContext: .
    healthCheckPath: /health.html
    envVars:
      - key: PORT
        value: 8080
